# Generated by Django 4.1.1 on 2023-03-21 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offense_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('offense', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('matric', models.CharField(max_length=250, unique=True)),
                ('department', models.CharField(blank=True, max_length=250, null=True)),
                ('punishment', models.CharField(max_length=250, unique=True)),
                ('pardon', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('ongoing', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True)),
            ],
        ),
    ]
