# Generated by Django 4.1.1 on 2023-04-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offenses',
            options={'ordering': ('offense',)},
        ),
        migrations.AlterField(
            model_name='offenses',
            name='matric',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='offenses',
            name='punishment',
            field=models.CharField(max_length=250),
        ),
    ]
